# Generated by Django 2.2.1 on 2020-08-06 12:31

from django.db import migrations, models
import djongo.models.fields
import input_data.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_03', models.IntegerField()),
                ('d_06', models.IntegerField()),
                ('d_09', models.IntegerField()),
                ('d_12', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Year_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_2019', djongo.models.fields.EmbeddedField(model_container=input_data.models.Quarter_data, null=True)),
                ('d_2018', djongo.models.fields.EmbeddedField(model_container=input_data.models.Quarter_data, null=True)),
                ('d_2017', djongo.models.fields.EmbeddedField(model_container=input_data.models.Quarter_data, null=True)),
                ('d_2016', djongo.models.fields.EmbeddedField(model_container=input_data.models.Quarter_data, null=True)),
                ('d_2015', djongo.models.fields.EmbeddedField(model_container=input_data.models.Quarter_data, null=True)),
                ('d_2014', djongo.models.fields.EmbeddedField(model_container=input_data.models.Quarter_data, null=True)),
                ('d_2013', djongo.models.fields.EmbeddedField(model_container=input_data.models.Quarter_data, null=True)),
                ('d_2012', djongo.models.fields.EmbeddedField(model_container=input_data.models.Quarter_data, null=True)),
                ('d_2011', djongo.models.fields.EmbeddedField(model_container=input_data.models.Quarter_data, null=True)),
                ('d_2010', djongo.models.fields.EmbeddedField(model_container=input_data.models.Quarter_data, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
